spring:
  application:
    name: photo-serv

server:
  port: 8080

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: nvm86ZedhgftVedpv0d5
  secretKey: LOkv0YZ1YSHk7gk2UtweZXKy3sY3hJ3fJhB6TqNS
  bucket: zjq-photos
  folderName: LightRoom 后期/

logging:
  level:
    root: INFO
    org.jiaqi.photoserv: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/photo-serv.log

#限制每秒最多一次请求
resilience4j.ratelimiter:
  instances:
    getPhotos:
      limitForPeriod: 5
      limitRefreshPeriod: PT1S
      timeoutDuration: PT1S

photo:
  upload:
    max-size: 10485760  # 最大文件大小（10MB）
    allowed-types: image/jpeg,image/png,image/gif  # 允许的文件类型